AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 45
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 45
  Exclude:
    - 'lib/parlant/client.rb'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/parlant/client.rb'

Style/Documentation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
